GestArtWeb/Controllers/Api/CategoriasController.cs
using GestArtWeb.Models;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Http;
using GestArtWeb.Dtos;
using AutoMapper;
using System;

namespace GestArtWeb.Controllers.Api
{
    public class CategoriasController : ApiController
    {
        private GestArtWebData db;

        public CategoriasController()
        {
            db = new GestArtWebData();
        }

        // GET /api/categorias
        public IHttpActionResult GetCategorias(string query = null)
        {
            var categoriasQuery = db.mage_categoria.OrderBy(c => c.nombre);

            if (!String.IsNullOrWhiteSpace(query))
                categoriasQuery = categoriasQuery.Where(c => c.nombre.Contains(query)).OrderBy(c => c.nombre);

            var categoriaDtos = categoriasQuery.ToList().Select(Mapper.Map<mage_categoria, CategoriaDto>);
            return Ok(categoriaDtos);
        }

        // GET /api/categorias/1
        public IHttpActionResult GetCategoria(int id)
        {
            var categoria = db.mage_categoria.SingleOrDefault(c => c.entity_id == id);

            if (categoria == null)
                return NotFound();

            return Ok(Mapper.Map<mage_categoria, CategoriaDto>(categoria));
        }

        // POST /api/categorias
        [HttpPost]
        public IHttpActionResult CreateCategoria(CategoriaDto categoriaDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var categoria = Mapper.Map<CategoriaDto, mage_categoria>(categoriaDto);

            db.mage_categoria.Add(categoria);
            db.SaveChanges();

            categoriaDto.entity_id = categoria.entity_id;

            return Created(new Uri(Request.RequestUri+"/"+categoria.entity_id), categoriaDto);
        }


        // PUT /api/categorias/1
        [HttpPut]
        public void UpdateCategoria(int id, CategoriaDto categoriaDto)
        {
            if (!ModelState.IsValid)
                throw new HttpResponseException(HttpStatusCode.BadRequest);

            var categoriaInDb = db.mage_categoria.SingleOrDefault(c => c.entity_id == id);

            if (categoriaInDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            Mapper.Map(categoriaDto, categoriaInDb);

            db.SaveChanges();
        }

        //DELETE /api/categorias/1
        [HttpDelete]
        public void DeleteCategoria(int id)
        {
            var categoriaInDb = db.mage_categoria.SingleOrDefault(c => c.entity_id == id);

            if (categoriaInDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            db.mage_categoria.Remove(categoriaInDb);
            db.SaveChanges();
        }

    }
}

GestArtWeb/Controllers/CategoriaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GestArtWeb.Models;
using GestArtWeb.Helper;
using MySql.Data.MySqlClient;

namespace GestArtWeb.Controllers
{
    public class CategoriaController : Controller
    {
        private GestArtWebData db = new GestArtWebData();
        private DbMySQLServer dbMysql = new DbMySQLServer();
        private const string QUERY_LAST_ENTITY_ID_ON_MAGENTO = "SELECT entity_id+1 FROM catalog_category_entity ORDER BY entity_id DESC LIMIT 1",
            //INSERT_HEAD_NEW_CATEGORY_ON_MAGENTO = "insert into catalog_category_entity values(@entityId, 3, 3, @parentId, now(), now(), (select* from (select concat(path,'/',@entityId) from catalog_category_entity where entity_id = @parentId) kk), (select* from (select position+1 from catalog_category_entity where parent_id = @parentId order by position desc limit 1) kk), @level, 0);",
            INSERT_OR_UPDATE_HEAD_CATEGORY_ON_MAGENTO = "insert into catalog_category_entity values(@entityId, 3,3, @parentId, now(), now(), (select* from (select concat(path,'/',@entityId) from catalog_category_entity where entity_id = @parentId) kk), (select* from (select count(*)+1 from catalog_category_entity where parent_id = @parentId) kk), @level, 0) ON DUPLICATE KEY UPDATE parent_id=@parentId, level=@level, path=(select* from (select concat(path,'/',@entityId) from catalog_category_entity where entity_id = @parentId) kk),position=(select* from (select position+1 from catalog_category_entity where parent_id = @parentId order by position desc limit 1) kk);",
            //INSERT_NAME_NEW_CATEGORY_ON_MAGENTO = "insert into catalog_category_entity_varchar values(null, 3, 41, 0, @entityId, @value);",
            INSERT_OR_UPDATE_NAME_CATEGORY_ON_MAGENTO = "INSERT INTO catalog_category_entity_varchar VALUES((select * from (select IF(count(*) > 0, value_id, null) from catalog_category_entity_varchar where entity_id = @entityId and attribute_id = 41) kk), 3, 41, 0, @entityId, @value) ON DUPLICATE KEY UPDATE value=@value;",
            //INSERT_ATTRIBUTE_INT_NEW_CATEGORY_ON_MAGENTO = "insert into catalog_category_entity_int values(null, 3, @attributeId, 0, @entityId, @value);";
            INSERT_OR_UPDATE_ATTRIBUTE_INT_CATEGORY_ON_MAGENTO = "insert into catalog_category_entity_int values((select * from (select if(count(*) > 0, value_id, null) from catalog_category_entity_varchar where entity_id = @entityId and attribute_id = @attributeId) kk), 3, @attributeId, 0, @entityId, @value) on duplicate key update value=@value;";
        private const int ATTRIBUTE_INCLUDE_IN_MENU = 67, ATTRIBUTE_IS_ACTIVE = 42, ATTRIBUTE_IS_ANCHOR = 51, ATTRIBUTE_NAME = 41;
        private int[] attributesInt = {ATTRIBUTE_INCLUDE_IN_MENU, ATTRIBUTE_IS_ACTIVE, ATTRIBUTE_IS_ANCHOR };

        // GET: Categoria
        public async Task<ActionResult> Index(int? page, string searchValue)
        {
            ViewData["SearchValue"] = !String.IsNullOrEmpty(searchValue) ? searchValue : "";
            var categories = db.mage_categoria.Where(c => c.entity_id != 1 && c.entity_id != 2).Include(m => m.mage_categoria2);

           if (!String.IsNullOrEmpty(searchValue))
            {
                categories = categories.Where(c => c.nombre.Contains(searchValue) || c.entity_id.ToString() == searchValue);
            }

            return PartialView(await Pagination<mage_categoria>.CreateAsync(categories.OrderBy(c => c.nivel).AsNoTracking(), page ?? 1, Pagination<mage_categoria>.PAGE_SIZE));
        }

        public async Task<ActionResult> ListFilter(string searchValue) {
            ViewData["SearchValue"] = !String.IsNullOrEmpty(searchValue) ? searchValue : "";
            var categories = db.mage_categoria.Where(c => c.entity_id != 1 && c.entity_id != 2).Include(m => m.mage_categoria2);

            if (!String.IsNullOrEmpty(searchValue))
            {
                categories = categories.Where(c => c.nombre.Contains(searchValue) || c.entity_id.ToString() == searchValue);
            }

            return PartialView("_ListFilter", await Pagination<mage_categoria>.CreateAsync(categories.OrderBy(c => c.entity_id).AsNoTracking(), 1, Pagination<mage_categoria>.PAGE_SIZE));
        }

        public FileContentResult ExportExcel()
        {
            List<mage_categoria> categories = db.mage_categoria.Where(c => c.entity_id != 1 && c.entity_id != 2).Include(m => m.mage_categoria2).OrderBy(c => c.nivel).ToList();

            string[,] columns = new string[,] { };

            byte[] filecontent = ExportToExcel.ExportExcel(ExportToExcel.ListCategoriesoDataTable(categories), "Categorías Web", columns);
            return File(filecontent, ExportToExcel.ExcelContentType, "categories.xlsx");
        }
        


        // GET: Categoria/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            mage_categoria mage_categoria = await db.mage_categoria.FindAsync(id);
            if (mage_categoria == null)
            {
                return HttpNotFound();
            }
            return View(mage_categoria);
        }

        // GET: Categoria/Details/5
        public async Task<ActionResult> SubCategorias(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            mage_categoria mage_categoria = await db.mage_categoria.FindAsync(id);
            if (mage_categoria == null)
            {
                return HttpNotFound();
            }
            return PartialView("_SubCategories",mage_categoria);
        }

        public async Task<ActionResult> ProductsOfCategory(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            mage_categoria mage_categoria = await db.mage_categoria.FindAsync(id);
            if (mage_categoria == null)
            {
                return HttpNotFound();
            }
            return PartialView("_ProductsOfCategory", mage_categoria);
        }

        // GET: Categoria/Create
        public ActionResult Create()
        {
            return PartialView();
        }

        private mage_categoria CreateNewCategory(mage_categoria parent, int newEntityAvailable, string name) {
            try
            {
                mage_categoria newCat = new mage_categoria();
                newCat.entity_id = newEntityAvailable;
                newCat.nombre = name;
                newCat.padre = parent.entity_id;
                newCat.es_activa = 1;
                newCat.es_anchor = 0;
                newCat.incluida_en_menu = 1;
                newCat.nivel = parent.nivel + 1;
                db.mage_categoria.Add(newCat);
                db.SaveChanges();
                return newCat;
            }
            catch (Exception ex)
            {
                return null;
            }
        }

        private int? GetNewEntityIdForCategory()
        {
            int? newEntityAvailable;
            try
            {
                newEntityAvailable = Convert.ToInt32(dbMysql.ExecuteSimpleQuery(QUERY_LAST_ENTITY_ID_ON_MAGENTO));
            }
            catch (Exception ex)
            {
                newEntityAvailable = null;
            }
            finally
            {
                dbMysql.Dispose();
            }
            return newEntityAvailable;
        }

        private bool? InsertOrUpdateçCategoryOnMagento(mage_categoria newCat)
        {
            List<QueryTransaction> queries = new List<QueryTransaction>();
            List<Parameter> Parameters = new List<Parameter>();

            Parameters.Add(new Parameter("@entityId", MySqlDbType.Int32, 5, 5, 0, newCat.entity_id));
            Parameters.Add(new Parameter("@parentId", MySqlDbType.Int32, 5, 5, 0, newCat.padre));
            Parameters.Add(new Parameter("@level", MySqlDbType.Int32, 5, 5, 0, newCat.nivel));
            queries.Add(new QueryTransaction(INSERT_OR_UPDATE_HEAD_CATEGORY_ON_MAGENTO, Parameter.CreateParametersMysql(Parameters)));
            Parameters.Clear();

            Parameters.Add(new Parameter("@entityId", MySqlDbType.Int32, 5, 5, 0, newCat.entity_id));
            Parameters.Add(new Parameter("@value", MySqlDbType.VarChar, 100, 5, 0, newCat.nombre));
            queries.Add(new QueryTransaction(INSERT_OR_UPDATE_NAME_CATEGORY_ON_MAGENTO, Parameter.CreateParametersMysql(Parameters)));
            Parameters.Clear();

            foreach (int attributeId in attributesInt)
            {
                Parameters.Add(new Parameter("@entityId", MySqlDbType.Int32, 5, 5, 0, newCat.entity_id));
                Parameters.Add(new Parameter("@attributeId", MySqlDbType.Int32, 5, 5, 0, attributeId));
                Parameters.Add(new Parameter("@value", MySqlDbType.Int32, 5, 5, 0, attributeId == ATTRIBUTE_INCLUDE_IN_MENU ? newCat.incluida_en_menu : attributeId == ATTRIBUTE_IS_ACTIVE ? newCat.es_activa : newCat.es_anchor));
                queries.Add(new QueryTransaction(INSERT_OR_UPDATE_ATTRIBUTE_INT_CATEGORY_ON_MAGENTO, Parameter.CreateParametersMysql(Parameters)));
                Parameters.Clear();
            }

            try
            {
                return dbMysql.ExecuteTransaction(queries);
            }
            catch (Exception ex)
            {
                return null;
            }

        }

        private bool DeteleCategory(mage_categoria cat)
        {
            try
            {
                db.mage_categoria.Remove(cat);
                db.SaveChanges();
                return true;
            }
            catch (Exception ex)
            {
                return false;
            }

GestArtWeb/Views/Categoria/Create.cshtml
<form id="formNewCategory" class="forms" style="display:none">
    <div class="form-group">
        <label for="name">Nombre de nueva categoría</label>
        <input type="text" class="form-control" id="nameCat" placeholder="..." name="name" required>
        <small class="form-text text-muted">Este será el nombre de la nueva categoría a crear.</small>
    </div>
    <div class="form-group">
        <label for="idPadre">Id de categoría padre</label>
        <input type="number" class="form-control" id="idPadre" placeholder="..." name="idPadre" required>
        <small class="form-text text-muted">Debe de introducir el codigo númerico que identifica a la categoría que quiere que se padre. Para ver los códigos de las categorías puede exportar en excel todas estas.</small>
    </div>
    <button type="submit" class="btn btn-primary" id="btnCreateNewCategoty">Crear</button>
    <div style="margin-top: 20px; height: 80px">
        <span id="loadingCreateCategory" style="display:none"><img src="~/fonts/loading45.gif" style="width:30px; height: 30px" /> Procesando... </span>
        <div class="card text-white bg-success mb-3" style="display:none">
            <div class="card-body">
                <p class="card-text" id="messageSuccessResultCreateCategory"></p>
            </div>
        </div>

        <div class="card text-white bg-danger mb-3" style="display:none">
            <div class="card-body">
                <p class="card-text" id="messageErrorResultCreateCategory"></p>
            </div>
        </div>
    </div>
</form>

GestArtWeb/Views/Categoria/Delete.cshtml
@model GestArtWeb.Models.mage_categoria

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>mage_categoria</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.es_activa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.es_activa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.es_anchor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.es_anchor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.incluida_en_menu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.incluida_en_menu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nivel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nivel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.familia_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.familia_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.modificado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.modificado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.mage_categoria2.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mage_categoria2.nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

GestArtWeb/Views/Categoria/Details.cshtml
@model GestArtWeb.Models.mage_categoria

@{
    ViewBag.Title = "Details";
}

<input type="hidden" value="@Model.entity_id" id="IdCategory"/>

<div class="container">
    <h4>Detalles de catagoría <span class="font-weight-bold">@Html.DisplayFor(model => model.entity_id)</span></h4>
    <hr />

    <div class="row m-2">
        <div class="card border-secondary mb-3 col-md-4 col-sm-12 p-0" style="height: 720px; max-height:720px;">
            <div class="card-header">
                Detalles
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Entity ID: <span class="font-weight-bold">@Html.DisplayFor(model => model.entity_id)</span></li>
                <li class="list-group-item">Nombre: <span class="font-weight-bold">@Html.DisplayFor(model => model.nombre)</span></li>
                <li class="list-group-item">
                    Activa:
                    @if (Model.es_activa == 1)
                    {<span class="font-weight-bold">Si</span> }
                    else
                    { <span class="font-weight-bold">No</span>}
                </li>
                <li class="list-group-item">Nivel: <span class="font-weight-bold">@Html.DisplayFor(model => model.nivel)</span></li>

                <li class="list-group-item">
                    Incluida en menú:
                    @if (Model.incluida_en_menu == 1)
                    {<span class="font-weight-bold">Si</span> }
                    else
                    { <span class="font-weight-bold">No</span>}
                </li>
                <li class="list-group-item">
                    Modificada:
                    @if (Model.modificado == 1)
                    {<span class="font-weight-bold">Si</span> }
                    else
                    { <span class="font-weight-bold">No</span>}
                </li>

                @if (Model.padre > 2)
                {


                    <li class="list-group-item">Padre ID: <span class="font-weight-bold">@Html.ActionLink(String.Format("{0}", Html.DisplayFor(model => model.mage_categoria2.entity_id)), "Details", "Categoria", new { id = Model.mage_categoria2.entity_id }, new { @class = "" })</span></li>
                    <li class="list-group-item">Nombre de Padre: <span class="font-weight-bold">@Html.ActionLink(String.Format("{0}", Html.DisplayFor(model => model.mage_categoria2.nombre)), "Details", "Categoria", new { id = Model.mage_categoria2.entity_id }, new { @class = "" })</span></li>
                }
                <li class="list-group-item">Nº de productos asociados: <span class="font-weight-bold">@Html.DisplayFor(model => model.mage_articulo.Count)</span></li>
                <li class="list-group-item">Nº de subcategorías: <span class="font-weight-bold">@Html.DisplayFor(model => model.mage_categoria1.Count)</span></li>

                <li class="list-group-item">Buscar Productos: <input type="text" class="form-control" disabled id="searchProduct" placeholder="Producto..." /></li>
                <li class="list-group-item">Buscar Subcatgoría: <input type="text" class="form-control" disabled id="searchSubCategoria" placeholder="Categoría..." /></li>
            </ul>
        </div>

        <div class="col-md-1 col-sm-offset-0"></div>

        <div class="card text-center col-md-7 col-sm-12 p-0 border-secondary" style="height:720px; max-height:720px ">
            <div class="card-header">
                <ul class="nav nav-tabs card-header-tabs">

                    <li class="nav-item">
                        <a class="nav-link active" href="#" id="btnSubCategories">Subcategorías</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#" id="btnProductOfCategories">Productos</a>
                    </li>


                </ul>
            </div>
            <div class="card-body p-0" id="cardBodyProductsAndCategories">

                @Html.Partial("_Subcategories")

            </div>
        </div>

    </div>



    <p class="mt-4">
        @Html.ActionLink("Editar", "Edit", new { id = Model.entity_id }) |
        @Html.ActionLink("Lista de categorías", "Index")
    </p>

</div>

GestArtWeb/Views/Categoria/ExportExcel.cshtml
@model GestArtWeb.Models.mage_categoria[]


<div id="listFiltered">
    <table class="table table-striped">
        <tr>
            <th>
                ID
            </th>
            <th>
                NOMBRE
            </th>
            <th>
                ID PADRE
            </th>
            <th>
                PADRE
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.entity_id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.mage_categoria2.entity_id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.mage_categoria2.nombre)
            </td>
        </tr>
        }

    </table>

</div>

GestArtWeb/Views/Categoria/Index.cshtml
@model GestArtWeb.Helper.Pagination<GestArtWeb.Models.mage_categoria>

@{
    ViewBag.Title = "Categorías";
}

<!--<div class="container"> -->

<!--
    <div class="row">
        <div class="col-lg-6 col-md-4 col-sm-12">
            <h2>Categorías</h2>
            <p>
                @Html.ActionLink("Crear nueva", "Create")
            </p>
        </div>
        <div class="col-lg-4 col-md-5 col-sm-12 mt-sm-1">
            <form class="form-inline">
                <div class="form-group">
                    <label for="searchValue" class="label-info">Buscar:</label>
                    <input type="text" id="searchValue" name="searchValue" class="form-control m-1" value="@ViewData["SearchValue"]" />
                </div>
            </form>
        </div>
        <div class="col-lg-2 col-md-2 cols-sm-12 mt-sm-1 mb-1">
            @Html.ActionLink("Exportar Excel", "ExportExcel", "Categoria", new { @class = "btn btn-outline-success " })
        </div>
    </div>
    -->

<div id="listFiltered">
    @Html.Partial("_ListFilter")
    @Html.ActionLink("Exportar Excel", "ExportExcel", "Categoria", new { }, new { @class = "btn btn-outline-success " })
</div>
    


    <!-- </div> -->


    @section scripts
{
        <script>
                    /*
                    $(document).ready(function () {
                        var cat = {};

                        var categories = new Bloodhound({
                            datumTokenizer: Bloodhound.tokenizers.obj.whitespace('nombre'),
                            queryTokenizer: Bloodhound.tokenizers.whitespace,
                            remote: {
                                url: '/api/categorias?query=%QUERY',
                                wildcard: '%QUERY'
                            }
                        });

                        $('#searchValue').typeahead({
                            minLength: 2,
                            highlight: true,
                            hint: false
                        }, {
                            name: 'catgorias',
                            display: 'nombre',
                            source: categories
                        }).on("typeahead:select", function (e, categoria) {
                            cat.entity_id = categoria.entity_id
                        });
                    });
                    */
        </script>

    }

GestArtWeb/Views/Categoria/_ListFilter.cshtml
@model GestArtWeb.Helper.Pagination<GestArtWeb.Models.mage_categoria>

<table class="table table-striped table-hover table-responsive-sm">
    <thead>
        <tr class="thead-dark">
            <th scope="col">
                ID
            </th>
            <th scope="col">
                NOMBRE
            </th>
            <th scope="col">
                ACTIVA
            </th>
            <th scope="col">
                NIVEL
            </th>
            <th scope="col">
                PADRE
            </th>

            <!-- <th></th> -->
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {

        <tr>
            <th scope="row">
                @item.entity_id
            </th>
            <td>
                @item.nombre
            </td>
            <td>

                @if (item.es_activa == 1)
                {
                    <span>Si</span>
                }
                else
                {
                    <span>No</span>
                }

            </td>
            <td>
                @{ var nivel = item.nivel - 1; }
                <span>@nivel º</span>

            </td>
            <td>
                @{
                    if (item.mage_categoria2.nivel > 1)
                    {
                        @item.mage_categoria2.nombre

                    }
                }

            </td>

            <!--
    <td>
        <div class="dropdown menuAction" style="display:inline-block">
            <span class="glyphicon glyphicon-option-vertical" style="cursor:pointer; width: 40px; padding-left:20px;" aria-hidden="true" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

            </span>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" style="left:-230px;">
                @Html.ActionLink("Ver", "Details", new { id = item.entity_id }, new { @class = "dropdown-item" })
                @Html.ActionLink("Editar", "Details", new { id = item.entity_id }, new { @class = "dropdown-item" })
                @Html.ActionLink("Desactivar", "Details", new { id = item.entity_id }, new { @class = "dropdown-item" })
                @Html.ActionLink("Ver lista de productos", "Details", new { id = item.entity_id }, new { @class = "dropdown-item" })
                @Html.ActionLink("Número total de productos", "Details", new { id = item.entity_id }, new { @class = "dropdown-item" })
                @Html.ActionLink("Añadir/Quitar un productos", "Details", new { id = item.entity_id }, new { @class = "dropdown-item" })
                @Html.ActionLink("Cambiar de padres", "Details", new { id = item.entity_id }, new { @class = "dropdown-item" })
            </div>
        </div>
    </td>
    -->
        </tr>
        }
    </tbody>

</table>

@{
    var prevDisabled = !Model.HasPreviosPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

@Html.ActionLink("Anterior", "Index", "Categoria", new { page = (@Model.PageIndex - 1), searchValue = ViewData["SearchValue"] }, new { @class = String.Format("btn btn-primary {0}", prevDisabled) })


@for (int i = 1; i <= Model.TotalPage; i++)
{
    @Html.ActionLink(String.Format("{0}", @i), "Index", "Categoria", new { page = @i, searchValue = ViewData["SearchValue"] }, new { @class = String.Format("btn btn-secondary m-1 item-pager {0}", @i == @Model.PageIndex ? "active" : "") })
}

@Html.ActionLink("Siguiente", "Index", "Categoria", new { page = (@Model.PageIndex + 1), searchValue = ViewData["SearchValue"] }, new { @class = String.Format("btn btn-primary {0}", nextDisabled) })

GestArtWeb/Views/Categoria/_ProductsOfCategory.cshtml
@model GestArtWeb.Models.mage_categoria

@if (Model.mage_articulo.Count > 0)
{
    <div class="card border-0" style="max-height:660px; overflow-y:scroll">
        <ul class="list-group list-group-flush">

            @foreach (var item in Model.mage_articulo)
            {
                <li class="list-group-item text-left">

                    @Html.ActionLink(String.Format("{0} | {1}", item.sku, item.mage_articulo_atributo_valor.SingleOrDefault(a => a.id_atributo == 71).value_varchar), "Details", "Producto", new { id = item.entity_id })

                </li>
            }

        </ul>
    </div>
}
else
{
    <h5 class="card-title mt-5">No se ha encontrado ningun producto.</h5>
    <p class="card-text">Para añadir productos, ha de editar clic en el botón Editar.</p>
    @Html.ActionLink("Editar", "Edit", "Producto", new { id = Model.entity_id }, new { @class = "btn btn-primary" })
}

GestArtWeb/Views/Categoria/_SubCategories.cshtml
@model GestArtWeb.Models.mage_categoria

@if (Model.mage_categoria1.Count > 0)
{
    <div class="card border-0" style="max-height:660px; overflow-y:scroll">
        <ul class="list-group list-group-flush">

            @foreach (var item in Model.mage_categoria1)
            {
                <li class="list-group-item text-left">

                    @Html.ActionLink(String.Format("{0} | {1}", item.entity_id, item.nombre), "Details", "Categoria", new { id = item.entity_id })

                </li>
            }

        </ul>
    </div>
}
else
{
    <h5 class="card-title mt-5">No se ha encontrado ninguna subcategorías.</h5>
    <p class="card-text">Para añadir una subcategoría ha de editar clic en el botón Editar.</p>
    @Html.ActionLink("Editar", "Edit", "Categoria", new { id = Model.entity_id }, new { @class = "btn btn-primary" })
}