GestArtWeb/Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GestArtWeb.Models;
using System.IO;
using Excel;
using System.Configuration;
using MySql.Data.MySqlClient;
using GestArtWeb.Helper;
using Renci.SshNet;
using System.Text.RegularExpressions;
using System.Web.Script.Serialization;
using Newtonsoft.Json;
using System.Web.Services;
using GestArtWeb.MagentoServices;
using System.Data.Entity.Infrastructure;

namespace GestArtWeb.Controllers
{
    public class ProductoController : Controller
    {
        private GestArtWebData db = new GestArtWebData();
        private DbMySQLServer dbMysql = null;
        private const string QUERY_INSERT_DATA_ATTRIBUTE_NEW_OR_UPDATE_MAGENTO = "INSERT INTO ad_new_update_product (sku,value,attributo_id,date_register,file_name) VALUES(@sku,@value,@atributo,@date,@fileName) ON DUPLICATE KEY UPDATE value=@value;";
        private const string QUERY_CALL_PROCEDURE_NEW_UPDATE_PRODUCT = "CALL ad_add_new_update_product(@p_date,@p_sku,@p_file_name);";
        private const string QUERY_DELETE_CATEGORY_IF_EXIST_FOR_PRODUCT = "DELETE FROM ad_new_update_product WHERE sku = @sku AND value = @value AND file_name = @fileName AND date_register = @date;";
        private const string QUERY_LAST_LOG_FOR_FILE = "SELECT status, message, date_error, file_name FROM ad_log_new_update_product WHERE IF(@p_date IS NOT NULL, date_error = @p_date, DATE(date_error)=DATE(NOW())) AND file_name = @p_file_name ORDER BY date_error DESC LIMIT 1;";
        private const string QUERY_GET_ENTITY_FOR_PRODUCT = "SELECT entity_id FROM catalog_product_entity WHERE sku=@sku;";
        private const int UPDATE_PROMOTIONS_YES = 1;
        private const int MANUFACTURE = 81;
        private const int PRICE = 75;
        private const int UNIDAD_ENVACE = 823;
        private const int STATUS = 96;
        private const int IS_MULTIPLE = 824;
        private const int EAN = 144;
        private const int PROMOTIONS = 139;
        private const int ORDEN = 836;
        private const int VISIBILITY = 102;
        private const int NAME = 71;
        private int[] COMMON_ATTRIBUTES = new int[] { MANUFACTURE, PRICE, UNIDAD_ENVACE, STATUS, IS_MULTIPLE, EAN, PROMOTIONS, ORDEN, VISIBILITY, NAME };
        private int TOTAL_ROW_IN_TABLE_COPY_DATA_PRODUCT = 20;

        [HttpPost]
        public JsonResult RefreshcumentProduct(string sku, string nameDoc) {
            MagentoServices.PortTypeClient clientMagentoWsdl = new PortTypeClient();
            var sesionMagentoWsdl = clientMagentoWsdl.login("alfadyser", "4lf4dys3r");

            var result = clientMagentoWsdl.call(
                sesionMagentoWsdl,
                "productos.producto",
                string.Format("<magento><producto><sku>{0}</sku><ficha_tecnica>{1}.pdf</ficha_tecnica></producto></magento>",sku,nameDoc)
                );

            clientMagentoWsdl.endSession(sesionMagentoWsdl);
            sesionMagentoWsdl = string.Empty;
            clientMagentoWsdl = null;

            return result.ToString().Contains("ERROR:") ? Json(0) : Json(1);
        }
        // GET: Producto
        public async Task<ActionResult> Index(bool ajaxQuery = false, string skuOrName = "")
        {
            IQueryable<mage_articulo> mage_articulo;
            if (skuOrName != String.Empty && skuOrName.Length > 0)
            {
                mage_articulo = db.mage_articulo.Where(p => p.sku.Length == 5 && (p.sku.Contains(skuOrName) || p.mage_articulo_atributo_valor.FirstOrDefault(a => a.id_atributo == 71).value_varchar.Contains(skuOrName)));
            }
            else
            {
                mage_articulo = db.mage_articulo.Where(m => m.sku.Length == 5).Include(m => m.mage_familia).Take(10);
            }
            if (ajaxQuery)
            {
                return PartialView(await mage_articulo.ToListAsync());
            }
            else
            {
                return View(await mage_articulo.ToListAsync());
            }
        }

        // GET: Producto/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            mage_articulo mage_articulo = await db.mage_articulo.FindAsync(id);
            if (mage_articulo == null)
            {
                return HttpNotFound();
            }
            return View(mage_articulo);
        }

        private bool IsItSomeCategoryColumn(string nameColumn)
        {
            return (nameColumn == "CAT1" || nameColumn == "CAT2" || nameColumn == "CAT3");
        }

        private string GetMessage(string message, List<string> args)
        {
            return String.Format(message, args.ToArray());
        }

        public DataTable LoadExcelInDataTable(HttpPostedFileBase uploadfile)
        {
            ViewData["messageError"] = null;
            if (uploadfile != null && uploadfile.ContentLength > 0)
            {
                //ExcelDataReader works on binary excel file
                Stream stream = uploadfile.InputStream;
                //We need to written the Interface.
                IExcelDataReader reader = null;
                if (uploadfile.FileName.EndsWith(".xls"))
                {
                    //reads the excel file with .xls extension
                    reader = ExcelReaderFactory.CreateBinaryReader(stream);
                }
                else if (uploadfile.FileName.EndsWith(".xlsx"))
                {
                    //reads excel file with .xlsx extension
                    reader = ExcelReaderFactory.CreateOpenXmlReader(stream);
                }
                else
                {
                    //Shows error if uploaded file is not Excel file
                    ViewData["messageError"] = Message.ERROR_FILE_NOT_TYPE_EXCEL;
                    return null;
                }
                //treats the first row of excel file as Coluymn Names
                reader.IsFirstRowAsColumnNames = true;
                //Adding reader data to DataSet()
                DataSet result = reader.AsDataSet();
                if (result.Tables.Count > 0)
                {
                    DataTable table = result.Tables[0];
                    table.TableName = uploadfile.FileName;
                    reader.Close();
                    return table;
                }
                else {
                    ViewData["messageError"] = Message.ERRO_EXCEL_NOT_CONTAIN_NO_ROW_DATA;
                    return null;
                }
            }else ViewData["messageError"] = Message.ERROR_FILE_NOT_SENT;

            return null;
        }

        private Task<bool> UploadProductosAttributesInTemporaryTableOnMagentoAsync(List<mage_articulo> articles, string fileName = null)
        {
            return Task.Run(() => UploadProductosAttributesInTemporaryTableOnMagento(articles, fileName));
        }
        private bool UploadProductosAttributesInTemporaryTableOnMagento(mage_articulo article, string fileName = null)
        {
            return UploadProductosAttributesInTemporaryTableOnMagento(new List<mage_articulo> { article }, fileName);
        }
        private bool UploadProductosAttributesInTemporaryTableOnMagento(List<mage_articulo> articles, string fileName = null)
        {
            bool someProductWasUploadCorrectly = false;
            var dbMysql = new DbMySQLServer();
            string date = DateTime.Today.ToString("yyyyMMdd");
            List<Parameter> parameters = new List<Parameter>();
            parameters.Add(new Parameter("@fileName", MySqlDbType.VarChar, 65532, 0, 0, fileName ?? String.Format("Subido sin Excel", date)));

            foreach (mage_articulo article in articles)
            {
                bool thereWasAnError = false;
                parameters.Add(new Parameter("@sku", MySqlDbType.VarChar, 5, 5, 0, article.sku));
                parameters.Add(new Parameter("@date", MySqlDbType.VarChar, 5, 5, 0, date));

                foreach (mage_articulo_atributo_valor attr in article.mage_articulo_atributo_valor)
                {
                    try
                    {
                        parameters.Add(new Parameter("@atributo", MySqlDbType.Int32, 5, 5, 0, attr.id_atributo));
                        var paramValue = new Parameter("@value", MySqlDbType.VarChar, 65532, 0, 0,
                                        attr.mage_atributo.tipo == "int"
                                            ? attr.value_int != null
                                                ? attr.mage_atributo.filtrable == 1 || attr.mage_atributo.id_atributo == 92
                                                    ? attr.mage_atributo.mage_atributo_opcion.FirstOrDefault(o => o.id_opcion == attr.value_int) != null
                                                        ? attr.mage_atributo.mage_atributo_opcion.FirstOrDefault(o => o.id_opcion == attr.value_int).valor
                                                        : ""
                                                    : attr.value_int.ToString()
                                                : ""
                                            : attr.mage_atributo.tipo == "decimal" ? attr.value_decimal != null ? attr.value_decimal.ToString().Replace(",",".") : ""
                                            : attr.mage_atributo.tipo == "varchar" ? attr.value_varchar != null ? attr.value_varchar : ""
                                            : attr.value_text != null ? attr.value_text : "");
                        parameters.Add(paramValue);

                        dbMysql.ExecuteSentenceCommand(QUERY_INSERT_DATA_ATTRIBUTE_NEW_OR_UPDATE_MAGENTO, Parameter.CreateParametersMysql(parameters));

                        parameters.RemoveRange(3, 2);
                    }

GestArtWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GestArtWeb</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    
</head>
<body>
    <!--add class  navbar-fixed-top-->

    <div class="sidebar">
        <h3>
            @Html.ActionLink("GestArtWeb", "Index", "Producto", new { area = "" }, new { @class = "nav-link viewProduct" })
        </h3>

        <div id="customMenu">
            <div id="menu">
                <ul>
                    <li>
                        @Html.ActionLink("Productos", "Index", "Producto", new { area = "" }, new { @class = "nav-link" })
                        <ul>
                            <li>
                                @Html.ActionLink("Ver", "Index", "Producto", new { area = "" }, new { id = "menu-item-view-products", @class = "nav-link" })
                            </li>
                            <li>
                                @Html.ActionLink("Crear", "Create", "Producto", new { area = "" }, new { id = "menu-item-create-product", @class = "nav-link" })
                            </li>
                            <li>
                                @Html.ActionLink("Actualizar fotos", "FormUpdatePhoto", "Producto", new { area = "" }, new { id = "menu-item-update-photo-product", @class = "nav-link" })
                            </li>
                        </ul>
                    </li>

                    <li>
                        @Html.ActionLink("Categoría", "Index", "Categoria", new { area = "" }, new { @class = "nav-link" })
                        <ul>
                            <li>
                                @Html.ActionLink("Ver", "Index", "Categoria", new { area = "" }, new { id="menu-item-view-categories", @class = "nav-link" })
                            </li>
                            <li>
                                @Html.ActionLink("Crear", "Create", "Categoria", new { area = "" }, new { id = "menu-item-create-category", @class = "nav-link" })
                            </li>
                            <li>
                                @Html.ActionLink("Modificar", "GetFormEdit", "Categoria", new { area = "" }, new { id = "menu-item-edit-category", @class = "nav-link" })
                            </li>
                        </ul>
                    </li>
                    <!--
                    <li>
                        <a href="#">Atributos</a>
                        <ul>
                            <li>
                                <a href="#">Ver</a>
                            </li>
                            <li>
                                <a href="#">Nuevo</a>
                            </li>
                            <li>
                                <a href="#">Modificar</a>
                            </li>
                        </ul>
                    </li>
                        -->
                </ul>
            </div>

        </div>


    </div>


    <div class="body-content">


        <div class="breadcrumbs-search">
            <img src="~/fonts/ico-menu2.png" class="img-responsive ico-menu" width="35" />

            <!--<div class="currently-showing">
                Navegando <span class="showing">298</span> <span class="category">of the best javascript plugins</span>
            </div>-->

            <div class="search">
                <form id="formSeach">
                    <span id="loadingSearchProduct" style="display:none"><img src="~/fonts/loading45.gif" style="width:30px; height: 30px" /> Buscando... </span>
                    <input type="text" placeholder="Buscar Producto" name="inputSearch" id="inputSearch" data-typeObjectToSearch="product">
                </form>
            </div>
        </div>

        <div id="content" class="p-3">
            <div id="resultAjax">
                @RenderBody()
            </div>
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Gestión de artículos web</p>
            </footer>
        </div>


    </div>



    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js" integrity="sha384-kW+oWsYx3YpxvjtZjFXqazFpA7UP/MbiY4jvs+RWZo2+N94PFZ36T6TFkc9O3qoB" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/scrollreveal"></script>
</body>
</html>

GestArtWeb/Views/Shared/_LoginPartialSpacelab.cshtml
@using Microsoft.AspNet.Identity
@if (Request.IsAuthenticated)
{
    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
    {
        @Html.AntiForgeryToken()

        <ul class="nav navbar-nav navbar-right">
            <li>
                @Html.ActionLink("Hello " + User.Identity.GetUserName() + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })
            </li>
            <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
        </ul>
    }
}
else
{

    <ul class="navbar-nav navbar-right">
        <li class="nav-item">
            @Html.ActionLink("Registro", "Register", "Account", new { area = "" }, new { @class = "nav-link" })
        </li>

        <li class="nav-item .justify-content-end">
            @Html.ActionLink("Iniciar sesión", "Login", "Account", new { area = "" }, new { @class = "nav-link", id = "loginLink" })
        </li>
    </ul>

}